// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIAKucttRQSlJu4ReYPVS6BProR6x22bA',
    appId: '1:960606932660:web:8b5cf71d20e3c1320fd1e1',
    messagingSenderId: '960606932660',
    projectId: 'fir-toturial-6897c',
    authDomain: 'fir-toturial-6897c.firebaseapp.com',
    storageBucket: 'fir-toturial-6897c.firebasestorage.app',
    measurementId: 'G-7W9Y8LY3EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUYzyL0HiT-yFUkFfUzuh5lzjRgHtZKWQ',
    appId: '1:960606932660:android:0e4e22db3875a2740fd1e1',
    messagingSenderId: '960606932660',
    projectId: 'fir-toturial-6897c',
    storageBucket: 'fir-toturial-6897c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIAhsFFN6ImGLQx9yxiGnMt96uKuX28Mw',
    appId: '1:960606932660:ios:9e8bd32a0fc860460fd1e1',
    messagingSenderId: '960606932660',
    projectId: 'fir-toturial-6897c',
    storageBucket: 'fir-toturial-6897c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIAhsFFN6ImGLQx9yxiGnMt96uKuX28Mw',
    appId: '1:960606932660:ios:9e8bd32a0fc860460fd1e1',
    messagingSenderId: '960606932660',
    projectId: 'fir-toturial-6897c',
    storageBucket: 'fir-toturial-6897c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIAKucttRQSlJu4ReYPVS6BProR6x22bA',
    appId: '1:960606932660:web:6a7482ddd8083c570fd1e1',
    messagingSenderId: '960606932660',
    projectId: 'fir-toturial-6897c',
    authDomain: 'fir-toturial-6897c.firebaseapp.com',
    storageBucket: 'fir-toturial-6897c.firebasestorage.app',
    measurementId: 'G-3RRBCCLFTH',
  );
}
